services:
  feature-flag-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feature-flag-api
    environment:
      STORAGE_ENDPOINT: "etcd:2379"
      DB_URL: "${DB_URL}"
      JWT_SECRET: "${JWT_SECRET}"
    ports:
      - "8080:8080"
    depends_on:
      # - etcd
      - postgres
    restart: unless-stopped

  etcd:
    image: quay.io/coreos/etcd:v3.5.13
    container_name: etcd
    environment:
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
    ports:
      - "2379:2379"
    volumes:
      - etcd_data:/etcd-data
    command:
      - /usr/local/bin/etcd
      - --data-dir=/etcd-data

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  etcd_data:
  postgres_data:
